    
apiVersion: v1
kind: Namespace
metadata:
  name: bittipannu-slack
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
  namespace: bittipannu-slack
spec:
  limits:
  - default:
      cpu: 300m
      memory: 512Mi
    defaultRequest:
      cpu: 0
      memory: 0
    type: Container